import turtle
tortuguita=turtle.Turtle()
tortuguita.pensize(15)
tortuguita.pencolor("Yellow")
tortuguita.shape("arrow")
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.right(120)
tortuguita.forward(50)
tortuguita.right(60)
tortuguita.forward(30)
tortuguita.right(65)
tortuguita.forward(45)

tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("light green")
tortuguita.penup()
tortuguita.goto((40, 0))
tortuguita.forward(20)
tortuguita.pendown()
tortuguita.left(80)
tortuguita.forward(70)
tortuguita.right(150)
tortuguita.forward(50)
tortuguita.pensize(12)
tortuguita.right(110)
tortuguita.forward(20)
tortuguita.pensize(15)
tortuguita.backward(20)
tortuguita.left(110)
tortuguita.forward(25)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("light blue")
tortuguita.penup()
tortuguita.goto((120, 0))
tortuguita.pendown()
tortuguita.left(110)
tortuguita.forward(70)
tortuguita.backward(70)
tortuguita.right(40)
tortuguita.forward(70)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("red")
tortuguita.penup()
tortuguita.goto((140, 0))
tortuguita.forward(20)
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(65)


tortuguita=turtle.Turtle()
tortuguita.shape("arrow")
tortuguita.pensize(15)
tortuguita.pencolor("light blue")
tortuguita.penup()
tortuguita.goto((180, 0))
tortuguita.pendown()
tortuguita.left(90)
tortuguita.forward(70)
tortuguita.right(120)
tortuguita.forward(50)
tortuguita.right(60)
tortuguita.forward(30)
tortuguita.right(65)
tortuguita.forward(45)


t=turtle.Turtle()
t.speed(0)
t.pencolor("black")
t.pensize(2)
for x in range (25):
    t.rt(40)
    for y in range (10):
        t.fd(15)
        t.rt(15)
    t.rt(90)
    for z in range (10):
        t.fd(15)
        t.rt(15)
    t.rt(40)